export {HomeView} from './home/HomeView'
export {LoginView } from './login/loginView'
export {RegisterView}  from './register/registerView'
export { ServicesView } from './services/index'
export { HoursView } from './hours/index'
export { ProfileView } from './profile/ProfileView'