@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlMmFmYzc2LTg1ZjAtNDRjYi1iZGJlLTY0NTJkYTMwZGUzZiIsImlhdCI6MTcxNjg2MjU4NywiZXhwIjoxNzE2ODY2MTg3fQ.3iHjx-iJgot7eW71UGYG8Ql1F9hN-rzXWCtT9AVL_Hc
POST http://localhost:3000/api/appointment
Content-Type: application/json

{
  "startDate": "2024-05-07T17:00:00",
  "total": 1000,
  "employee_id": "53aa4769-829b-4a02-9a60-3011aee05403",
  "user_id": "53aa4769-829b-4a02-9a60-3011aee05409",
  "services": [
    "8cf59fd9-a442-492c-bef3-a3af8ae7c18f",
    "90c6c522-f7fb-437d-bcb3-f5b58d7ea267"
    ]

}

###
GET http://localhost:3000/api/appointment
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/appointment/company
Authorization: Bearer {{token}}
