@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlMmFmYzc2LTg1ZjAtNDRjYi1iZGJlLTY0NTJkYTMwZGUzZiIsImlhdCI6MTcxNjg2MjU4NywiZXhwIjoxNzE2ODY2MTg3fQ.3iHjx-iJgot7eW71UGYG8Ql1F9hN-rzXWCtT9AVL_Hc
POST http://localhost:3000/api/company
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "address": "Av mongolito",
  "avatar": null,
  "name": "Barber Simulator",
  "phone_number": "+569"
}